site_name: FastAPI
site_description: FastAPI framework, high performance, easy to learn, fast to code, ready for production

theme:
    name: 'material'
    palette:
      primary: 'teal'
      accent: 'amber'
    logo: 'img/icon-white.svg'
    favicon: 'img/favicon.png'

repo_name: tiangolo/fastapi
repo_url: https://github.com/tiangolo/fastapi
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Features: 'features.md'
    - Tutorial:
        - Tutorial Intro: 'tutorial/intro.md'
        - First Steps: 'tutorial/first-steps.md'
        - Path Parameters: 'tutorial/path-params.md'
        - Query Parameters: 'tutorial/query-params.md'
        - Request Body: 'tutorial/body.md'
        - Query Parameters - String Validations: 'tutorial/query-params-str-validations.md'
        - Path Parameters - Numeric Validations: 'tutorial/path-params-numeric-validations.md'
        - Body - Multiple Parameters: 'tutorial/body-multiple-params.md'
        - Body - Schema: 'tutorial/body-schema.md'
        - Body - Nested Models: 'tutorial/body-nested-models.md'
        - Cookie Parameters: 'tutorial/cookie-params.md'
        - Header Parameters: 'tutorial/header-params.md'
        - Response Model: 'tutorial/response-model.md'
        - Extra Models: 'tutorial/extra-models.md'
        - Form Data: 'tutorial/request-forms.md'
        - Request Files: 'tutorial/request-files.md'
        - Request Forms and Files: 'tutorial/request-forms-and-files.md'
        - Path Operation Configuration: 'tutorial/path-operation-configuration.md'
        - Path Operation Advanced Configuration: 'tutorial/path-operation-advanced-configuration.md'
    - Concurrency and async / await: 'async.md'
    - Deployment: 'deployment.md'
    

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
