[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "fastapi"
author = "Sebastián Ramírez"
author-email = "tiangolo@gmail.com"
home-page = "https://github.com/tiangolo/fastapi"
classifiers = ["License :: OSI Approved :: MIT License"]
requires = [
    "starlette >=0.9.7",
    "pydantic >=0.16"
]
requires-python = ">=3.6"

[tool.flit.metadata.requires-extra]
test = [
    "pytest >=4.0.0",
    "pytest-cov",
    "mypy",
    "black",
    "isort",
    "requests"
]
doc = [
    "mkdocs",
    "mkdocs-material",
    "markdown-include"
]
dev = [
    "prospector",
    "rope"
]
all = [
    "requests",
    "aiofiles",
    "jinja2",
    "python-multipart",
    "itsdangerous",
    "pyyaml",
    "graphene",
    "ujson",
    "ujson",
    "email_validator",
    "uvicorn",
]
