name: Watch Docs Previews
on:
  schedule:
    - cron: "* * * * *"

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/watch-previews
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
